import { CSSProperties, memo } from "react";
import type { SpaceTheme } from "../greetbot/spaceThemes";
import { SpaceContainer } from "./stars.style";

type StarsBackgroundProps = {
    theme: SpaceTheme;
};

const WARP_STREAKS = [
    { delay: "-0.4s", duration: "2.2s", height: "2px", left: "2%", opacity: 0.88, top: "12%", width: "11rem" },
    { delay: "-1.1s", duration: "2.8s", height: "1px", left: "9%", opacity: 0.68, top: "28%", width: "16rem" },
    { delay: "-2.6s", duration: "2.4s", height: "2px", left: "16%", opacity: 0.84, top: "20%", width: "9rem" },
    { delay: "-1.7s", duration: "3.1s", height: "1px", left: "23%", opacity: 0.72, top: "44%", width: "18rem" },
    { delay: "-3.2s", duration: "2.3s", height: "2px", left: "31%", opacity: 0.9, top: "18%", width: "12rem" },
    { delay: "-0.9s", duration: "3.4s", height: "1px", left: "39%", opacity: 0.62, top: "58%", width: "20rem" },
    { delay: "-2.1s", duration: "2.6s", height: "2px", left: "45%", opacity: 0.82, top: "34%", width: "10rem" },
    { delay: "-1.5s", duration: "3s", height: "1px", left: "52%", opacity: 0.7, top: "14%", width: "15rem" },
    { delay: "-2.8s", duration: "2.1s", height: "2px", left: "60%", opacity: 0.9, top: "24%", width: "13rem" },
    { delay: "-0.6s", duration: "3.2s", height: "1px", left: "67%", opacity: 0.64, top: "46%", width: "19rem" },
    { delay: "-3.6s", duration: "2.5s", height: "2px", left: "74%", opacity: 0.82, top: "16%", width: "9rem" },
    { delay: "-1.2s", duration: "2.9s", height: "1px", left: "81%", opacity: 0.74, top: "30%", width: "14rem" },
    { delay: "-2.4s", duration: "2.2s", height: "2px", left: "88%", opacity: 0.86, top: "52%", width: "11rem" },
    { delay: "-3.9s", duration: "3.3s", height: "1px", left: "94%", opacity: 0.56, top: "22%", width: "17rem" },
] as const;

const WARP_STARS = [
    { delay: "-1.2s", duration: "4.2s", left: "4%", opacity: 0.64, size: "0.42rem", top: "16%" },
    { delay: "-2.8s", duration: "5.1s", left: "13%", opacity: 0.52, size: "0.26rem", top: "34%" },
    { delay: "-0.9s", duration: "3.8s", left: "18%", opacity: 0.76, size: "0.34rem", top: "48%" },
    { delay: "-3.4s", duration: "5.4s", left: "26%", opacity: 0.58, size: "0.24rem", top: "24%" },
    { delay: "-1.6s", duration: "4.6s", left: "33%", opacity: 0.72, size: "0.38rem", top: "14%" },
    { delay: "-2.2s", duration: "5.3s", left: "41%", opacity: 0.5, size: "0.22rem", top: "42%" },
    { delay: "-0.7s", duration: "4s", left: "48%", opacity: 0.8, size: "0.44rem", top: "58%" },
    { delay: "-2.9s", duration: "5.6s", left: "56%", opacity: 0.54, size: "0.24rem", top: "20%" },
    { delay: "-1.4s", duration: "4.4s", left: "61%", opacity: 0.72, size: "0.36rem", top: "32%" },
    { delay: "-3.1s", duration: "5.2s", left: "68%", opacity: 0.6, size: "0.28rem", top: "12%" },
    { delay: "-0.8s", duration: "4.1s", left: "74%", opacity: 0.74, size: "0.4rem", top: "52%" },
    { delay: "-2.5s", duration: "5.8s", left: "82%", opacity: 0.46, size: "0.22rem", top: "38%" },
    { delay: "-1.1s", duration: "4.7s", left: "89%", opacity: 0.7, size: "0.34rem", top: "18%" },
    { delay: "-3.7s", duration: "5s", left: "95%", opacity: 0.56, size: "0.24rem", top: "46%" },
] as const;

const ASTEROID_FIELD = [
    {
        delay: "-5s",
        driftX: "2.8rem",
        driftY: "-1.8rem",
        duration: "19s",
        heightRatio: "0.76",
        left: "-4%",
        opacity: 0.9,
        radius: "58% 42% 64% 36% / 42% 58% 44% 56%",
        rotate: "-18deg",
        size: "11rem",
        top: "8%",
        variant: "large",
        zIndex: 1,
    },
    {
        delay: "-8s",
        driftX: "1.9rem",
        driftY: "-1rem",
        duration: "24s",
        heightRatio: "0.72",
        left: "5%",
        opacity: 0.82,
        radius: "46% 54% 51% 49% / 38% 46% 54% 62%",
        rotate: "14deg",
        size: "4.4rem",
        top: "26%",
        variant: "medium",
        zIndex: 1,
    },
    {
        delay: "-2s",
        driftX: "2.4rem",
        driftY: "-1.6rem",
        duration: "22s",
        heightRatio: "0.7",
        left: "12%",
        opacity: 0.88,
        radius: "54% 46% 59% 41% / 49% 39% 61% 51%",
        rotate: "-12deg",
        size: "7rem",
        top: "16%",
        variant: "large",
        zIndex: 1,
    },
    {
        delay: "-9s",
        driftX: "1.4rem",
        driftY: "-0.8rem",
        duration: "27s",
        heightRatio: "0.68",
        left: "19%",
        opacity: 0.72,
        radius: "44% 56% 52% 48% / 53% 41% 59% 47%",
        rotate: "8deg",
        size: "2.6rem",
        top: "42%",
        variant: "small",
        zIndex: 1,
    },
    {
        delay: "-4s",
        driftX: "2.6rem",
        driftY: "-1.4rem",
        duration: "21s",
        heightRatio: "0.78",
        left: "26%",
        opacity: 0.9,
        radius: "61% 39% 48% 52% / 42% 59% 41% 58%",
        rotate: "-22deg",
        size: "9rem",
        top: "9%",
        variant: "large",
        zIndex: 1,
    },
    {
        delay: "-11s",
        driftX: "1.6rem",
        driftY: "-1rem",
        duration: "25s",
        heightRatio: "0.74",
        left: "36%",
        opacity: 0.8,
        radius: "47% 53% 63% 37% / 55% 37% 63% 45%",
        rotate: "16deg",
        size: "4.8rem",
        top: "24%",
        variant: "medium",
        zIndex: 1,
    },
    {
        delay: "-7s",
        driftX: "1.2rem",
        driftY: "-0.6rem",
        duration: "28s",
        heightRatio: "0.66",
        left: "44%",
        opacity: 0.62,
        radius: "58% 42% 45% 55% / 46% 52% 48% 54%",
        rotate: "-8deg",
        size: "1.8rem",
        top: "54%",
        variant: "shard",
        zIndex: 1,
    },
    {
        delay: "-6s",
        driftX: "2.2rem",
        driftY: "-1.2rem",
        duration: "20s",
        heightRatio: "0.75",
        left: "52%",
        opacity: 0.9,
        radius: "52% 48% 58% 42% / 36% 58% 42% 64%",
        rotate: "-10deg",
        size: "7.4rem",
        top: "14%",
        variant: "large",
        zIndex: 1,
    },
    {
        delay: "-13s",
        driftX: "1.8rem",
        driftY: "-1rem",
        duration: "26s",
        heightRatio: "0.7",
        left: "61%",
        opacity: 0.76,
        radius: "45% 55% 49% 51% / 59% 36% 64% 41%",
        rotate: "12deg",
        size: "3.8rem",
        top: "34%",
        variant: "medium",
        zIndex: 1,
    },
    {
        delay: "-3s",
        driftX: "2.6rem",
        driftY: "-1.5rem",
        duration: "23s",
        heightRatio: "0.74",
        left: "69%",
        opacity: 0.92,
        radius: "62% 38% 55% 45% / 40% 60% 40% 60%",
        rotate: "-16deg",
        size: "10rem",
        top: "8%",
        variant: "large",
        zIndex: 1,
    },
    {
        delay: "-10s",
        driftX: "1.4rem",
        driftY: "-0.9rem",
        duration: "29s",
        heightRatio: "0.69",
        left: "78%",
        opacity: 0.74,
        radius: "49% 51% 57% 43% / 45% 57% 43% 55%",
        rotate: "10deg",
        size: "5.2rem",
        top: "40%",
        variant: "medium",
        zIndex: 1,
    },
    {
        delay: "-5s",
        driftX: "2.1rem",
        driftY: "-1.4rem",
        duration: "21s",
        heightRatio: "0.77",
        left: "86%",
        opacity: 0.88,
        radius: "56% 44% 63% 37% / 38% 52% 48% 62%",
        rotate: "-14deg",
        size: "8.2rem",
        top: "16%",
        variant: "large",
        zIndex: 1,
    },
    {
        delay: "-14s",
        driftX: "2.8rem",
        driftY: "-1.6rem",
        duration: "27s",
        heightRatio: "0.78",
        left: "94%",
        opacity: 0.84,
        radius: "43% 57% 52% 48% / 55% 37% 63% 45%",
        rotate: "18deg",
        size: "11.6rem",
        top: "48%",
        variant: "large edge",
        zIndex: 1,
    },
    {
        delay: "-7s",
        driftX: "1.8rem",
        driftY: "-1.1rem",
        duration: "24s",
        heightRatio: "0.72",
        left: "14%",
        opacity: 0.78,
        radius: "57% 43% 51% 49% / 46% 61% 39% 54%",
        rotate: "-11deg",
        size: "6.4rem",
        top: "64%",
        variant: "large",
        zIndex: 1,
    },
    {
        delay: "-12s",
        driftX: "1.6rem",
        driftY: "-0.7rem",
        duration: "26s",
        heightRatio: "0.68",
        left: "34%",
        opacity: 0.66,
        radius: "52% 48% 40% 60% / 63% 42% 58% 37%",
        rotate: "7deg",
        size: "2.4rem",
        top: "68%",
        variant: "small",
        zIndex: 1,
    },
    {
        delay: "-6s",
        driftX: "2rem",
        driftY: "-1.1rem",
        duration: "22s",
        heightRatio: "0.74",
        left: "47%",
        opacity: 0.8,
        radius: "60% 40% 46% 54% / 48% 57% 43% 52%",
        rotate: "-15deg",
        size: "5.8rem",
        top: "62%",
        variant: "medium",
        zIndex: 1,
    },
    {
        delay: "-9s",
        driftX: "2.3rem",
        driftY: "-1.3rem",
        duration: "23s",
        heightRatio: "0.73",
        left: "63%",
        opacity: 0.82,
        radius: "46% 54% 61% 39% / 43% 58% 42% 57%",
        rotate: "13deg",
        size: "7.2rem",
        top: "68%",
        variant: "large",
        zIndex: 1,
    },
    {
        delay: "-15s",
        driftX: "1.2rem",
        driftY: "-0.8rem",
        duration: "30s",
        heightRatio: "0.67",
        left: "81%",
        opacity: 0.62,
        radius: "54% 46% 49% 51% / 51% 47% 53% 49%",
        rotate: "-9deg",
        size: "1.6rem",
        top: "60%",
        variant: "shard",
        zIndex: 1,
    },
] as const;

const getWarpStyle = (warp: (typeof WARP_STREAKS)[number]) =>
    ({
        "--warp-delay": warp.delay,
        "--warp-duration": warp.duration,
        "--warp-height": warp.height,
        "--warp-left": warp.left,
        "--warp-opacity": warp.opacity,
        "--warp-top": warp.top,
        "--warp-width": warp.width,
    }) as CSSProperties;

const getWarpStarStyle = (star: (typeof WARP_STARS)[number]) =>
    ({
        "--warp-star-delay": star.delay,
        "--warp-star-duration": star.duration,
        "--warp-star-left": star.left,
        "--warp-star-opacity": star.opacity,
        "--warp-star-size": star.size,
        "--warp-star-top": star.top,
    }) as CSSProperties;

const getAsteroidStyle = (asteroid: (typeof ASTEROID_FIELD)[number]) =>
    ({
        "--asteroid-delay": asteroid.delay,
        "--asteroid-drift-x": asteroid.driftX,
        "--asteroid-drift-y": asteroid.driftY,
        "--asteroid-duration": asteroid.duration,
        "--asteroid-height-ratio": asteroid.heightRatio,
        "--asteroid-left": asteroid.left,
        "--asteroid-opacity": asteroid.opacity,
        "--asteroid-radius": asteroid.radius,
        "--asteroid-rotate": asteroid.rotate,
        "--asteroid-size": asteroid.size,
        "--asteroid-top": asteroid.top,
        "--asteroid-z-index": asteroid.zIndex,
    }) as CSSProperties;

export const StarsBackground = memo(({ theme }: StarsBackgroundProps) => (
    <SpaceContainer $theme={theme} aria-hidden="true">
        {theme === "space"
            ? WARP_STREAKS.map((warp, index) => (
                  <span className="warp-streak" key={`warp-streak-${index}`} style={getWarpStyle(warp)} />
              ))
            : null}

        {theme === "space"
            ? WARP_STARS.map((star, index) => (
                  <span className="warp-star" key={`warp-star-${index}`} style={getWarpStarStyle(star)} />
              ))
            : null}

        {theme === "asteroids"
            ? ASTEROID_FIELD.map((asteroid, index) => (
                  <span
                      className={`asteroid-field-rock ${asteroid.variant}`}
                      key={`asteroid-${index}`}
                      style={getAsteroidStyle(asteroid)}
                  />
              ))
            : null}
    </SpaceContainer>
));
